//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ConsoleApplication2
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ClaimsOneLiveEntitiesS : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ClaimsOneLiveEntitiesS object using the connection string found in the 'ClaimsOneLiveEntitiesS' section of the application configuration file.
        /// </summary>
        public ClaimsOneLiveEntitiesS() : base("name=ClaimsOneLiveEntitiesS", "ClaimsOneLiveEntitiesS")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ClaimsOneLiveEntitiesS object.
        /// </summary>
        public ClaimsOneLiveEntitiesS(string connectionString) : base(connectionString, "ClaimsOneLiveEntitiesS")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ClaimsOneLiveEntitiesS object.
        /// </summary>
        public ClaimsOneLiveEntitiesS(EntityConnection connection) : base(connection, "ClaimsOneLiveEntitiesS")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AssignedJob> AssignedJobs
        {
            get
            {
                if ((_AssignedJobs == null))
                {
                    _AssignedJobs = base.CreateObjectSet<AssignedJob>("AssignedJobs");
                }
                return _AssignedJobs;
            }
        }
        private ObjectSet<AssignedJob> _AssignedJobs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Holiday> Holidays
        {
            get
            {
                if ((_Holidays == null))
                {
                    _Holidays = base.CreateObjectSet<Holiday>("Holidays");
                }
                return _Holidays;
            }
        }
        private ObjectSet<Holiday> _Holidays;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AssignedJobs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAssignedJobs(AssignedJob assignedJob)
        {
            base.AddObject("AssignedJobs", assignedJob);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Holidays EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHolidays(Holiday holiday)
        {
            base.AddObject("Holidays", holiday);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClaimsOneLiveModelS", Name="AssignedJob")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AssignedJob : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AssignedJob object.
        /// </summary>
        /// <param name="assignedJobId">Initial value of the AssignedJobId property.</param>
        /// <param name="jobNumber">Initial value of the JobNumber property.</param>
        /// <param name="cSRCode">Initial value of the CSRCode property.</param>
        public static AssignedJob CreateAssignedJob(global::System.Int32 assignedJobId, global::System.String jobNumber, global::System.String cSRCode)
        {
            AssignedJob assignedJob = new AssignedJob();
            assignedJob.AssignedJobId = assignedJobId;
            assignedJob.JobNumber = jobNumber;
            assignedJob.CSRCode = cSRCode;
            return assignedJob;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AssignedJobId
        {
            get
            {
                return _AssignedJobId;
            }
            set
            {
                if (_AssignedJobId != value)
                {
                    OnAssignedJobIdChanging(value);
                    ReportPropertyChanging("AssignedJobId");
                    _AssignedJobId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AssignedJobId");
                    OnAssignedJobIdChanged();
                }
            }
        }
        private global::System.Int32 _AssignedJobId;
        partial void OnAssignedJobIdChanging(global::System.Int32 value);
        partial void OnAssignedJobIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String JobNumber
        {
            get
            {
                return _JobNumber;
            }
            set
            {
                OnJobNumberChanging(value);
                ReportPropertyChanging("JobNumber");
                _JobNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("JobNumber");
                OnJobNumberChanged();
            }
        }
        private global::System.String _JobNumber;
        partial void OnJobNumberChanging(global::System.String value);
        partial void OnJobNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CSRCode
        {
            get
            {
                return _CSRCode;
            }
            set
            {
                OnCSRCodeChanging(value);
                ReportPropertyChanging("CSRCode");
                _CSRCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CSRCode");
                OnCSRCodeChanged();
            }
        }
        private global::System.String _CSRCode;
        partial void OnCSRCodeChanging(global::System.String value);
        partial void OnCSRCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VehicleNumber
        {
            get
            {
                return _VehicleNumber;
            }
            set
            {
                OnVehicleNumberChanging(value);
                ReportPropertyChanging("VehicleNumber");
                _VehicleNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VehicleNumber");
                OnVehicleNumberChanged();
            }
        }
        private global::System.String _VehicleNumber;
        partial void OnVehicleNumberChanging(global::System.String value);
        partial void OnVehicleNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> AssignedDateTime
        {
            get
            {
                return _AssignedDateTime;
            }
            set
            {
                OnAssignedDateTimeChanging(value);
                ReportPropertyChanging("AssignedDateTime");
                _AssignedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AssignedDateTime");
                OnAssignedDateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _AssignedDateTime;
        partial void OnAssignedDateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnAssignedDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Info1
        {
            get
            {
                return _Info1;
            }
            set
            {
                OnInfo1Changing(value);
                ReportPropertyChanging("Info1");
                _Info1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Info1");
                OnInfo1Changed();
            }
        }
        private global::System.String _Info1;
        partial void OnInfo1Changing(global::System.String value);
        partial void OnInfo1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Info2
        {
            get
            {
                return _Info2;
            }
            set
            {
                OnInfo2Changing(value);
                ReportPropertyChanging("Info2");
                _Info2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Info2");
                OnInfo2Changed();
            }
        }
        private global::System.String _Info2;
        partial void OnInfo2Changing(global::System.String value);
        partial void OnInfo2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Info3
        {
            get
            {
                return _Info3;
            }
            set
            {
                OnInfo3Changing(value);
                ReportPropertyChanging("Info3");
                _Info3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Info3");
                OnInfo3Changed();
            }
        }
        private global::System.String _Info3;
        partial void OnInfo3Changing(global::System.String value);
        partial void OnInfo3Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClaimsOneLiveModelS", Name="Holiday")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Holiday : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Holiday object.
        /// </summary>
        /// <param name="holidayId">Initial value of the HolidayId property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        public static Holiday CreateHoliday(global::System.Int32 holidayId, global::System.DateTime date)
        {
            Holiday holiday = new Holiday();
            holiday.HolidayId = holidayId;
            holiday.Date = date;
            return holiday;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HolidayId
        {
            get
            {
                return _HolidayId;
            }
            set
            {
                if (_HolidayId != value)
                {
                    OnHolidayIdChanging(value);
                    ReportPropertyChanging("HolidayId");
                    _HolidayId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("HolidayId");
                    OnHolidayIdChanged();
                }
            }
        }
        private global::System.Int32 _HolidayId;
        partial void OnHolidayIdChanging(global::System.Int32 value);
        partial void OnHolidayIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Info1
        {
            get
            {
                return _Info1;
            }
            set
            {
                OnInfo1Changing(value);
                ReportPropertyChanging("Info1");
                _Info1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Info1");
                OnInfo1Changed();
            }
        }
        private global::System.String _Info1;
        partial void OnInfo1Changing(global::System.String value);
        partial void OnInfo1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Info2
        {
            get
            {
                return _Info2;
            }
            set
            {
                OnInfo2Changing(value);
                ReportPropertyChanging("Info2");
                _Info2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Info2");
                OnInfo2Changed();
            }
        }
        private global::System.String _Info2;
        partial void OnInfo2Changing(global::System.String value);
        partial void OnInfo2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Info3
        {
            get
            {
                return _Info3;
            }
            set
            {
                OnInfo3Changing(value);
                ReportPropertyChanging("Info3");
                _Info3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Info3");
                OnInfo3Changed();
            }
        }
        private global::System.String _Info3;
        partial void OnInfo3Changing(global::System.String value);
        partial void OnInfo3Changed();

        #endregion

    
    }

    #endregion

    
}
