//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaimsOneWindowsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignedJob
    {
        public int AssignedJobId { get; set; }
        public string JobNumber { get; set; }
        public string CSRCode { get; set; }
        public string VehicleNumber { get; set; }
        public Nullable<System.DateTime> AssignedDateTime { get; set; }
        public string Info1 { get; set; }
        public string Info2 { get; set; }
        public string Info3 { get; set; }
    }
}
